"""add_analysis_fields

Revision ID: 132c5c7db4b1
Revises: a9b053c24ab7
Create Date: 2026-04-09 19:08:15.955265

"""
from alembic import op
import sqlalchemy as sa


revision = '132c5c7db4b1'
down_revision = 'a9b053c24ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('translated_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('analysis_status', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('analysis_error', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'analyzed_at')
    op.drop_column('documents', 'analysis_error')
    op.drop_column('documents', 'analysis_status')
    op.drop_column('documents', 'translated_text')
    op.drop_column('documents', 'ocr_text')
    # ### end Alembic commands ###
