"""add_roadmap_items

Revision ID: 1a75dd4da6a9
Revises: 56cf3b322765
Create Date: 2026-04-09 16:20:46.040613

"""
from alembic import op
import sqlalchemy as sa


revision = '1a75dd4da6a9'
down_revision = '56cf3b322765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('idea', 'planned', 'in_progress', 'done', 'on_hold', name='featurestatus'), nullable=False),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='featurepriority'), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('linked_modules', sa.JSON(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap_items')
    # ### end Alembic commands ###
