"""add_manual_transcription

Revision ID: bdc5247b48b9
Revises: ec407d420146
Create Date: 2026-04-09 22:29:13.066083

"""
from alembic import op
import sqlalchemy as sa


revision = 'bdc5247b48b9'
down_revision = 'ec407d420146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('manual_transcription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'manual_transcription')
    # ### end Alembic commands ###
