"""add_extracted_fields

Revision ID: ec407d420146
Revises: 132c5c7db4b1
Create Date: 2026-04-09 20:41:38.444270

"""
from alembic import op
import sqlalchemy as sa


revision = 'ec407d420146'
down_revision = '132c5c7db4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_fields')
    # ### end Alembic commands ###
